CREATE SCHEMA IF NOT EXISTS kafka_connect;

CREATE TABLE kafka_connect.login_registry (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(255),
    dateon timestamp DEFAULT current_timestamp
);

INSERT INTO kafka_connect.login_registry ("username")
values
    ('Иванов'),
    ('Петров'),
    ('Герасимов'),
    ('Симонов');